apiVersion: v1
kind: Pod
metadata:
  name: postgres-client
spec:
  containers:
  - name: postgres-client
    image: postgres:latest
    command: ["/bin/bash", "-c"]
    args:
    - |
      apt-get update && apt-get install -y screen
      sleep infinity
    envFrom:
    - secretRef:
        name: postgres-readwrite-svcbind