nameOverride: nginx

ingress:
  enabled: true
  className: nginx
  host: files.dev.testingmachine.eu
  tls:
    enabled: false
    secretName: files-tls-secret
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "300m"
    
persistence:
  enabled: true
  storageClass: "gp3"   # change to your StorageClass
  accessMode: ReadWriteOnce
  size: 5Gi
  mountPath: /data