nameOverride: nginx

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "300m"
  tls:
    - hosts:
      - files.dev.testingmachine.eu
      secretName: tls-files
  hosts:
    - host: files.dev.testingmachine.eu
      paths: 
        - path: "/"
          pathType: Prefix
    
persistence:
  enabled: true
  storageClass: "gp3"   # change to your StorageClass
  accessMode: ReadWriteOnce
  size: 5Gi
  mountPath: /data