# use legacy image due to bitnami deprecation
image:
  repository: bitnamilegacy/mongodb
  tag: 7.0.5-debian-11-r3
global:
  security:
    allowInsecureImages: true

# https://artifacthub.io/packages/helm/bitnami/mongodb
fullnameOverride: mongodb

# Switch to ReplicaSet architecture.
architecture: replicaset

# Allocate at least one replica for each AZ.
replicaCount: 3

# Ensure that each pod is scheduled to a different node.
podAntiAffinityPreset: hard

# ! NOTE: values of `auth.replicaSetKey` and `auth.rootPassword` must be passed
#         via command-line during `helm install` or `helm upgrade` operations.

# Set up authentication.
auth:
  enabled: true

# initdbScripts:
#   init.js: |
#    db.addUser...

# We create this manually and don't need it for root.
# serviceBindings:
#  enabled: true

persistence:
  size: 32Gi

resources:
  limits:
    cpu: 1000m  # 1000m is equivalent to 1 CPU core
    # Consider that mongodb sets it's default cache size when starting up to 50% of (max memory - 1GB)
    # In practice, this means that mongo will constantly occupy at least roughly half of what you are setting as limit here
    memory: 3Gi
  requests:
    cpu: 500m   # 500m is equivalent to 0.5 CPU core
    memory: 1Gi # set this to  (limits.memory - 1Gi) / 2

arbitrer:
  resources:
    limits:
      cpu: 100m # 100m is equivalent to 0.1 CPU core
      memory: 500Mi
    requests:
      cpu: 50m  # 50m is equivalent to 0.05 CPU core
      memory: 150Mi
